# Generated by Django 5.1.6 on 2025-02-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="jd_document",
            field=models.FileField(blank=True, null=True, upload_to="jd_files/"),
        ),
    ]
